package com.deckwatch.core.database.mappers

import com.deckwatch.core.database.entity.EquipmentEntity
import com.deckwatch.core.model.Equipment

fun EquipmentEntity.toModel(): Equipment = Equipment(
    id = id,
    vesselId = vesselId,
    deckId = deckId,
    zoneId = zoneId,
    parentId = parentId,
    typeKey = typeKey,
    symbolKey = symbolKey,
    tag = tag,
    name = name,
    location = location,
    posX = posX,
    posY = posY,
    rotationDeg = rotationDeg,
    makerName = makerName,
    modelName = modelName,
    serialNumber = serialNumber,
    typeApprovalNumber = typeApprovalNumber,
    manufactureDate = manufactureDate,
    installedDate = installedDate,
    quantity = quantity,
    condition = condition,
    conditionSetAt = conditionSetAt,
    statusFlag = statusFlag,
    attributesJson = attributesJson,
    nextDueDate = nextDueDate,
    nextDueTaskKey = nextDueTaskKey,
    photoUris = photoUris,
    notes = notes,
    createdAt = createdAt,
    updatedAt = updatedAt,
    deletedAt = deletedAt,
)

fun Equipment.toEntity(): EquipmentEntity = EquipmentEntity(
    id = id,
    vesselId = vesselId,
    deckId = deckId,
    zoneId = zoneId,
    parentId = parentId,
    typeKey = typeKey,
    symbolKey = symbolKey,
    tag = tag,
    name = name,
    location = location,
    posX = posX,
    posY = posY,
    rotationDeg = rotationDeg,
    makerName = makerName,
    modelName = modelName,
    serialNumber = serialNumber,
    typeApprovalNumber = typeApprovalNumber,
    manufactureDate = manufactureDate,
    installedDate = installedDate,
    quantity = quantity,
    condition = condition,
    conditionSetAt = conditionSetAt,
    statusFlag = statusFlag,
    attributesJson = attributesJson,
    nextDueDate = nextDueDate,
    nextDueTaskKey = nextDueTaskKey,
    photoUris = photoUris,
    notes = notes,
    createdAt = createdAt,
    updatedAt = updatedAt,
    deletedAt = deletedAt,
)
